package com.tasks.restservice.TasksRestService.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import com.tasks.restservice.TasksRestService.models.User;
import com.tasks.restservice.TasksRestService.repositories.UserRepository;

@RestController    // This means that this class is a Controller
@RequestMapping(path="/tasks/api/users") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping()
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @PostMapping()
    public @ResponseBody String newUser(@RequestParam("name") String name,
        @RequestParam("password") String passw,
        @RequestParam("email") String email) {

        User n = new User();
        n.setName(name);
        n.setPassword(passw);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }
}
